<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="P_Stack" Id="{6d895120-20ec-4ebe-b215-006e9cde9ef5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Stack
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Dynamic_Array_Stack();
P_Linked_List_Stack();

]]></ST>
    </Implementation>
    <LineIds Name="P_Stack">
      <LineId Id="5" Count="1" />
      <LineId Id="33" Count="0" />
      <LineId Id="30" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>