<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="P_Queue" Id="{56cfd7ab-2ed9-4783-a5e7-8ebb28be2ed0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Queue
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Dynamic_Array_Queue();
P_Linked_List_Queue();]]></ST>
    </Implementation>
    <LineIds Name="P_Queue">
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>