<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{86dc0999-fc6b-4ce8-a12d-7649401b850c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	aArray : ARRAY[0..4] OF INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Linked_List();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>