<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="P_Linked_List" Id="{f61c3acb-991b-491b-b0a4-6beac0b2bf6d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Linked_List
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Singly_Linked_List();
//P_Doubly_Linked_List();]]></ST>
    </Implementation>
    <LineIds Name="P_Linked_List">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>