<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Base_Stack" Id="{8bc58612-cbbe-4e93-b171-775069cb599d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Base_Stack IMPLEMENTS I_Stack
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Peek" Id="{172dc61e-e2a8-48a9-ae38-b6a973d240ec}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Peek : T_DATA_TYPE
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Pop" Id="{f233d5b4-3108-4337-b281-dc937455ad33}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Pop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Push" Id="{354dceed-21d1-48bb-bcb2-2026d0a92934}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Push
VAR_INPUT
	Data	: T_DATA_TYPE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Show" Id="{6e723a8f-bd16-42eb-9cf9-40357cb7d068}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Show
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Base_Stack">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Base_Stack.Peek">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Base_Stack.Pop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Base_Stack.Push">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Base_Stack.Show">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>