<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Dynamic_Stack" Id="{6794da22-5d0c-48e6-b3a8-88d57cbb32b9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Dynamic_Stack IMPLEMENTS I_Stack
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Peek" Id="{2eb5ed08-a9b0-4fdc-a4fc-6c6b26d9bcd6}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Peek : T_DATA_TYPE
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Pop" Id="{bbedc7b5-0295-4ee8-ac30-b3b8281ee07b}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Pop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Push" Id="{1192dd04-d4fd-4b27-af4d-9615dea0bc87}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Push
VAR_INPUT
	Data	: T_DATA_TYPE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Show" Id="{4fb0df02-3ae9-4af9-9983-b8822a8b4e2e}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Show
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Dynamic_Stack">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Dynamic_Stack.Peek">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Dynamic_Stack.Pop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Dynamic_Stack.Push">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Dynamic_Stack.Show">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>