<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Linked_List_Stack" Id="{2c59cdc2-33c5-4868-bca4-01c093a816a0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Linked_List_Stack IMPLEMENTS I_Stack
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Peek" Id="{c2639508-4e31-4b41-ba23-49c69940227c}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Peek : T_DATA_TYPE
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Pop" Id="{859ccdaa-4bef-4e52-91c9-55ee71ff56a8}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Pop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Push" Id="{bedbe239-212f-42b1-8e7c-4d2a523feac0}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Push
VAR_INPUT
	Data	: T_DATA_TYPE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Show" Id="{24bc1739-b5a7-45aa-816d-caa104c39755}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Show
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Linked_List_Stack">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Linked_List_Stack.Peek">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Linked_List_Stack.Pop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Linked_List_Stack.Push">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Linked_List_Stack.Show">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>