<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Circular_Linked_List" Id="{e5e30373-35c0-41e7-8063-7b279ed7852a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Circular_Linked_List IMPLEMENTS I_Linked_List
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Create" Id="{2ac95a10-90c1-47b2-a710-c702a67dc8f7}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Creates/Adds an node to the end of the list*)
METHOD Create
VAR_INPUT
	(* Data to add to new node.*)
	Data	: T_DATA_TYPE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Empty" Id="{f6e4621c-2fc7-457b-838b-73c20443d6c7}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Empties/Clears/Deletes list*)
METHOD Empty
	pTemp	: POINTER TO ST_NODE;
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Init" Id="{e9745e9b-3ee4-4686-91ed-3babf04c5955}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Initializes or create an empty list*)
METHOD Init
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Insert" Id="{5a89d366-e123-4ccb-9f6b-5db6e0f597ec}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Inserts node at a specific position in the list*)
METHOD Insert
VAR_INPUT
	(* Data to add to new node.*)
	Data	: T_DATA_TYPE;
	(* Position to add new node in list.*)
	nPosition	: UXINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Pop" Id="{a626d5b9-8d21-45b5-9ea7-c41dab304206}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Pop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Push" Id="{08caf6df-f63f-426d-88fa-55d24a8d7f89}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Push
VAR_INPUT
	Data	: T_DATA_TYPE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Remove" Id="{4bda5e3a-2995-4e74-9a3f-c9e520f66c74}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Deletes node at a specific position in the list*)
METHOD Remove
VAR_INPUT
	(* Position of node to delete.*)
	nPosition	: UXINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Search" Id="{e2823435-c9a7-465e-8280-643ba0498997}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Searches list for the first instance of data and returns it's location and whether it's in the list.*)
METHOD Search : BOOL
VAR_INPUT
	(* Data to find in list*)
	Data	: T_DATA_TYPE;
END_VAR
VAR_OUTPUT
	(* Location of the data  starting from 1. 0 means data is not found in list*)
	nPosition	: UXINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Show" Id="{76fa360d-788d-4af9-a33b-06c0b7d048fd}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Show
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Size" Id="{4dd8311e-e575-4e7d-a3e3-5b7936c57771}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Gets size of the list*)
METHOD Size : UXINT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Circular_Linked_List">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Create">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Empty">
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Init">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Insert">
      <LineId Id="11" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Pop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Push">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Remove">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Search">
      <LineId Id="13" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Show">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Circular_Linked_List.Size">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>