<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Doubly_Linked_List" Id="{03f6cb54-b49e-4d08-867b-b49ddd590b59}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Doubly_Linked_List IMPLEMENTS I_Linked_List
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Create" Id="{6e81400d-b895-4d17-b1a0-7da2503c1458}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Creates/Adds an node to the end of the list*)
METHOD Create
VAR_INPUT
	(* Data to add to new node.*)
	Data	: T_DATA_TYPE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Empty" Id="{13b07b7d-29f4-462f-80ab-63c642c8cda8}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Empties/Clears/Deletes list*)
METHOD Empty
	pTemp	: POINTER TO ST_NODE;
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Init" Id="{28f1b4fd-cd0a-476e-b533-29fe33ce49ad}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Initializes or create an empty list*)
METHOD Init
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Insert" Id="{a2deca27-6648-4030-8273-4c1592694cd7}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Inserts node at a specific position in the list*)
METHOD Insert
VAR_INPUT
	(* Data to add to new node.*)
	Data	: T_DATA_TYPE;
	(* Position to add new node in list.*)
	nPosition	: UXINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Pop" Id="{57f6bc23-5136-40d5-b964-533e7903d35d}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Pop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Push" Id="{6bda1aa4-b07a-470f-b437-14107fdbde7f}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Push
VAR_INPUT
	Data	: T_DATA_TYPE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Remove" Id="{6e058adb-4972-4a7b-a117-85ef4a2c1908}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Deletes node at a specific position in the list*)
METHOD Remove
VAR_INPUT
	(* Position of node to delete.*)
	nPosition	: UXINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Search" Id="{c1b15b75-1452-4c17-83dd-a4eb41b967d7}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Searches list for the first instance of data and returns it's location and whether it's in the list.*)
METHOD Search : BOOL
VAR_INPUT
	(* Data to find in list*)
	Data	: T_DATA_TYPE;
END_VAR
VAR_OUTPUT
	(* Location of the data  starting from 1. 0 means data is not found in list*)
	nPosition	: UXINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Show" Id="{8dbf6dac-001b-468c-bddc-48e5342ec7ae}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Show
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Size" Id="{99c2f4dd-ee7e-4556-89ac-f7318d382c33}">
      <Declaration><![CDATA[{warning 'add method implementation '}
(* Gets size of the list*)
METHOD Size : UXINT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Doubly_Linked_List">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Create">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Empty">
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Init">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Insert">
      <LineId Id="11" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Pop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Push">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Remove">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Search">
      <LineId Id="13" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Show">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Doubly_Linked_List.Size">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>